// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPh3z3jVodwEwUIFLhLxtsSGMb0DuWEjc',
    appId: '1:276186497276:web:2fb10124eab38da4ca5779',
    messagingSenderId: '276186497276',
    projectId: 'academico-itsi-f1c88',
    authDomain: 'academico-itsi-f1c88.firebaseapp.com',
    storageBucket: 'academico-itsi-f1c88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuewMnajaBMgPI4ID4oP4057sGDr4Njm0',
    appId: '1:276186497276:android:3cb91b8b7ab2d02eca5779',
    messagingSenderId: '276186497276',
    projectId: 'academico-itsi-f1c88',
    storageBucket: 'academico-itsi-f1c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8el6FTGinec0CMcVN8osw4f1x3UcNfA',
    appId: '1:276186497276:ios:4ddbc7251053193eca5779',
    messagingSenderId: '276186497276',
    projectId: 'academico-itsi-f1c88',
    storageBucket: 'academico-itsi-f1c88.firebasestorage.app',
    iosBundleId: 'com.example.appAcademico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL8el6FTGinec0CMcVN8osw4f1x3UcNfA',
    appId: '1:276186497276:ios:4ddbc7251053193eca5779',
    messagingSenderId: '276186497276',
    projectId: 'academico-itsi-f1c88',
    storageBucket: 'academico-itsi-f1c88.firebasestorage.app',
    iosBundleId: 'com.example.appAcademico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPh3z3jVodwEwUIFLhLxtsSGMb0DuWEjc',
    appId: '1:276186497276:web:e4789d5a94834079ca5779',
    messagingSenderId: '276186497276',
    projectId: 'academico-itsi-f1c88',
    authDomain: 'academico-itsi-f1c88.firebaseapp.com',
    storageBucket: 'academico-itsi-f1c88.firebasestorage.app',
  );

}